-- defines for groups
Group{
    name='Admin',
    disallow={
        'edit_permission_group',
        'delete_permission_group',
        'add_permission_group'
    }
}

Group{
    name='HiMember',
    disallow={
        'edit_permission_group',
        'delete_permission_group',
        'add_permission_group'
    }
}

Group{
    name='Member',
    disallow={
        'edit_permission_group',
        'delete_permission_group',
        'add_permission_group',
        'set_auto_launch_rocket',
        'change_programmable_speaker_alert_parameters',
        'drop_item'
    }
}

Group{
    name='User',
    disallow={
        'edit_permission_group',
        'delete_permission_group',
        'add_permission_group',
        'set_auto_launch_rocket',
        'change_programmable_speaker_alert_parameters',
        'drop_item',
        'build_terrain',
        'remove_cables',
        'launch_rocket',
        'reset_assembling_machine',
        'cancel_research'
    }
}

Group{
    name='Jail',
    disallow={
        'set_allow_commands',
        'edit_permission_group',
        'delete_permission_group',
        'add_permission_group',
        'open_character_gui',
        'begin_mining',
        'start_walking',
        'player_leave_game',
        'open_blueprint_library_gui',
        'build_item',
        'use_item',
        'select_item',
        'rotate_entity',
        'open_train_gui',
        'open_train_station_gui',
        'open_gui',
        'open_item',
        'deconstruct',
        'build_rail',
        'cancel_research',
        'start_research',
        'set_train_stopped',
        'select_gun',
        'open_technology_gui',
        'open_trains_gui',
        'edit_custom_tag',
        'craft',
        'setup_assembling_machine',
    }
}