--- Res Settings
-- @config Research

return {
    enabled = true,
    pollution_ageing_by_research = false,
    queue_amount = 3,
    -- this enable 20 more inventory for each mining productivity level up to 4
    bonus_inventory = {
        enabled = true,
        name = 'character_inventory_slots_bonus',
        rate = 5,
        limit = 20
    },
    file_name = 'log/research.log',
    milestone = {
        ['automation'] = 600,
        ['logistics'] = 300,
        ['steel-processing'] = 300,
        ['logistic-science-pack'] = 300,
        ['electronics'] = 300,
        ['fast-inserter'] = 300,
        ['steel-axe'] = 300,
        ['automation-2'] = 300,
        ['advanced-material-processing'] = 300,
        ['engine'] = 300,
        ['fluid-handling'] = 300,
        ['oil-processing'] = 300,
        ['sulfur-processing'] = 300,
        ['plastics'] = 300,
        ['advanced-electronics'] = 300,
        ['chemical-science-pack'] = 300,
        ['modules'] = 300,
        ['logistics-2'] = 300,
        ['railway'] = 300,
        ['research-speed-1'] = 300,
        ['research-speed-2'] = 300,
        ['battery'] = 300,
        ['concrete'] = 300,
        ['flammables'] = 300,
        ['low-density-structure'] = 300,
        ['advanced-material-processing-2'] = 300,
        ['productivity-module'] = 300,
        ['production-science-pack'] = 300,
        ['advanced-electronics-2'] = 300,
        ['advanced-oil-processing'] = 300,
        ['electric-engine'] = 300,
        ['robotics'] = 300,
        ['construction-robotics'] = 300,
        ['worker-robots-speed-1'] = 300,
        ['worker-robots-speed-2'] = 300,
        ['utility-science-pack'] = 300,
        ['productivity-module-2'] = 300,
        ['speed-module-2'] = 300,
        ['rocket-fuel'] = 300,
        ['effect-transmission'] = 300,
        ['productivity-module-3'] = 300,
        ['rocket-control-unit'] = 300,
        ['speed-module-3'] = 300,
        ['rocket-silo'] = 300,
        ['space-science-pack'] = 300,
    },
    inf_res = {
        -- Mining Productivity
        ['mining-productivity-4'] = 4,
        -- Robot Speed
        ['worker-robots-speed-6'] = 6,
        -- Laser Damage
        ['energy-weapons-damage-7'] = 7,
        -- Explosive Damage
        ['stronger-explosives-7'] = 7,
        -- Bullet Damage
        ['physical-projectile-damage-7'] = 7,
        -- Flame Damage
        ['refined-flammables-7'] = 7,
        -- Artillery Range
        ['artillery-shell-range-1'] = 1,
        -- Artillery Speed
        ['artillery-shell-speed-1'] = 1
    }
}
