{
 "title": "#Infos",
 "description": "Some live-stats for the Brave New World series",
 "tags": [ "factorio" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "nodePort", "query": "9100" },
   { "name": "jobName", "query": "dev" }
  ]
 },
 "panels": [
  { "title": "Base", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Game Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "factorio_tick{instance=\"localhost:$nodePort\", job=\"$jobName\"}/60"
    }
   ]
  },
  {
   "title": "Players Online",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "factorio_online_players{instance=\"localhost:$nodePort\", job=\"$jobName\"}"
    }
   ]
  },
  {
   "title": "Factorio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "factorio_mods{name=\"base\", instance=\"localhost:$nodePort\", job=\"$jobName\"}==1"
    }
   ]
  },
  {
   "title": "Mods",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "factorio_mods{name!=\"base\", name!=\"graftorio\", name!=\"AwF-Scenario\", name!~\"tvc_.*\", instance=\"localhost:$nodePort\", job=\"$jobName\"}==1"
    }
   ]
  },
  {
   "title": "Seed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "factorio_seed{instance=\"localhost:$nodePort\", job=\"$jobName\"}"
    }
   ]
  },
  {
   "title": "Evolution",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "factorio_evolution{force=\"enemy\", type=\"total\", instance=\"localhost:$nodePort\", job=\"$jobName\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Evolution Composition",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "factorio_evolution{force=\"enemy\", type!=\"total\", instance=\"localhost:$nodePort\", job=\"$jobName\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(factorio_evolution{force=\"enemy\", type!=\"total\", instance=\"localhost:$nodePort\", job=\"$jobName\"})",
     "legendFormat": "Sum"
    }
   ]
  },
  { "title": "Research", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Research",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "factorio_research_queue{index=\"1\", instance=\"localhost:$nodePort\", job=\"$jobName\"}",
     "legendFormat": "{{localised_name}}: {{level}}"
    }
   ]
  },
  {
   "title": "Research Queue",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "factorio_research_queue{index!=\"1\",force=\"player\", instance=\"localhost:$nodePort\", job=\"$jobName\"}"
    }
   ]
  },
  { "title": "Rockets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Rockets launched",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "factorio_items_launched_total{instance=\"localhost:$nodePort\", job=\"$jobName\"}",
     "legendFormat": "Rockets launched",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Rockets / hour",
   "type": "stat",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_items_launched_total{instance=\"localhost:$nodePort\", job=\"$jobName\"}[5m])*80*60",
     "legendFormat": "Rockets / hour",
     "target": "randomWalk('myName')"
    }
   ]
  },
  { "title": "Kills / minute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Biters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(factorio_kill_count_input{name=~\".*-spawner\", instance=\"localhost:$nodePort\", job=\"prometheus\"}[5m])*80)",
     "legendFormat": "Spawner"
    },
    {
     "expr": "sum(rate(factorio_kill_count_input{name=~\".*-turret\", instance=\"localhost:$nodePort\", job=\"prometheus\"}[5m])*80)",
     "legendFormat": "Turret"
    },
    {
     "expr": "sum(rate(factorio_kill_count_input{name=~\"small.*\", instance=\"localhost:$nodePort\", job=\"prometheus\"}[5m])*80)",
     "legendFormat": "Small"
    },
    {
     "expr": "sum(rate(factorio_kill_count_input{name=~\"medium.*\", instance=\"localhost:$nodePort\", job=\"prometheus\"}[5m])*80)",
     "legendFormat": "Medium"
    },
    {
     "expr": "sum(rate(factorio_kill_count_input{name=~\"big.*\", instance=\"localhost:$nodePort\", job=\"prometheus\"}[5m])*80)",
     "legendFormat": "Big"
    },
    {
     "expr": "sum(rate(factorio_kill_count_input{name=~\"behemoth.*\", instance=\"localhost:$nodePort\", job=\"prometheus\"}[5m])*80)",
     "legendFormat": "Behemoth"
    }
   ]
  },
  {
   "title": "Casualties",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(factorio_kill_count_output{name=~\".*-robot\", instance=\"localhost:$nodePort\", job=\"prometheus\"}[5m])*80)",
     "legendFormat": "Robots"
    },
    {
     "expr": "sum(rate(factorio_kill_count_output{name=\"stone-wall\", instance=\"localhost:$nodePort\", job=\"prometheus\"}[5m])*80)",
     "legendFormat": "Walls"
    },
    {
     "expr": "sum(rate(factorio_kill_count_output{name=~\".*-turret\", instance=\"localhost:$nodePort\", job=\"prometheus\"}[5m])*80)",
     "legendFormat": "Turrets"
    },
    {
     "expr": "sum(rate(factorio_kill_count_output{name!~\".*-worm-.*\", name!~\".*biter.*\", name!~\".*spitter.*\", name!~\"tree-.*\", name!~\".*rock-.*\", name!~\"nilaus-.*\", name!~\".*-robot\", name!=\"stone-wall\", name!~\".*-turret\", instance=\"localhost:$nodePort\", job=\"prometheus\"}[1m])*80)",
     "legendFormat": "Base"
    }
   ]
  }
 ]
}