{
 "title": "Production",
 "description": "Some live-stats for the AwF Test Server",
 "tags": [ "factorio" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "nodePort", "query": "9100" },
   { "name": "jobName", "query": "dev" }
  ]
 },
 "panels": [
  { "title": "Science / minute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Red",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"automation-science-pack\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[1m])*80",
     "legendFormat": "Red",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Green",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"logistic-science-pack\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[1m])*80",
     "legendFormat": "Green",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Blue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"chemical-science-pack\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[1m])*80",
     "legendFormat": "Blue",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Purple",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"production-science-pack\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[1m])*80",
     "legendFormat": "Purple",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Yellow",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"utility-science-pack\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[1m])*80",
     "legendFormat": "Yellow",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Space",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"space-science-pack\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[5m])*80",
     "legendFormat": "Rocket",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Military",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"military-science-pack\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[5m])*80",
     "legendFormat": "Rocket",
     "target": "randomWalk('myName')"
    }
   ]
  },
  { "title": "Circuits / minute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Green",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"electronic-circuit\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[1m])*80",
     "legendFormat": "Green",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Red",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"advanced-circuit\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[1m])*80",
     "legendFormat": "Red",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Blue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"processing-unit\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[1m])*80",
     "legendFormat": "Blue",
     "target": "randomWalk('myName')"
    }
   ]
  },
  { "title": "Materials / minute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Iron",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"iron-plate\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[1m])*80",
     "legendFormat": "Iron",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Copper",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"copper-plate\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[1m])*80",
     "legendFormat": "Copper",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Plastic",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"plastic-bar\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[1m])*80",
     "legendFormat": "Plastic",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Steel",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"steel-plate\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[1m])*80",
     "legendFormat": "Steel",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Stone Bricks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"stone-brick\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[1m])*80",
     "legendFormat": "Steel",
     "target": "randomWalk('myName')"
    }
   ]
  },
  { "title": "Components / minute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"battery\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[1m])*80",
     "legendFormat": "Battery",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Flying Robot Frame",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"flying-robot-frame\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[1m])*80",
     "legendFormat": "Flying Robot Frame",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Low Density Structure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"low-density-structure\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[2m])*80",
     "legendFormat": "Low Density Structure",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Rocket Control Unit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"rocket-control-unit\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[2m])*80",
     "legendFormat": "Rocket Control Unit",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Rocket Fuel",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_input{name=\"rocket-fuel\", instance=\"localhost:$nodePort\", job=\"$jobName\"}[2m])*80",
     "legendFormat": "Rocket Fuel",
     "target": "randomWalk('myName')"
    }
   ]
  }
 ]
}