{
 "title": "Robots",
 "tags": [ "factorio" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "nodePort", "query": "9100" },
   { "name": "jobName", "query": "dev" }
  ]
 },
 "panels": [
  {
   "title": "Total Construction Bots",
   "type": "stat",
   "description": "This is a current total for the last time the data was provided",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "factorio_logistics_bots{type=\"all_construction_robots\", network_type=\"roboport\", instance=\"localhost:$nodePort\", job=\"$jobName\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Logistic Bots",
   "type": "stat",
   "description": "This is a current total for the last time the data was provided",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "factorio_logistics_bots{type=\"all_logistic_robots\", network_type=\"roboport\", instance=\"localhost:$nodePort\", job=\"$jobName\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Charging Bots",
   "type": "stat",
   "description": "This is an average over the past 5m",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(factorio_logistics_bots{type=\"charging_bots\", network_type=\"roboport\", instance=\"localhost:$nodePort\", job=\"$jobName\"})"
    }
   ]
  },
  {
   "title": "Requested",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_join(label_replace( (factorio_logistics_items{request_type=\"deliver\", instance=\"localhost:$nodePort\", job=\"$jobName\"}>0), \"icon\", \"icon[$1]\", \"name\", \"(.*)\"), \"name_w_icon\", \" \", \"icon\", \"localised_name\")"
    }
   ]
  },
  {
   "title": "Available Construction Bots",
   "type": "stat",
   "description": "This is a current total for the last time the data was provided",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(factorio_logistics_bots{type=\"available_construction_robots\", network_type=\"roboport\", instance=\"localhost:$nodePort\", job=\"$jobName\"})"
    }
   ]
  },
  {
   "title": "Available Logistic Bots",
   "type": "stat",
   "description": "This is a current total for the last time the data was provided",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(factorio_logistics_bots{type=\"available_logistic_robots\", network_type=\"roboport\", instance=\"localhost:$nodePort\", job=\"$jobName\"})"
    }
   ]
  },
  {
   "title": "Bots Waiting for Charge",
   "type": "stat",
   "description": "This is an average over the past 5m",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(factorio_logistics_bots{type=\"waiting_for_charge\", network_type=\"roboport\", instance=\"localhost:$nodePort\", job=\"$jobName\"})"
    }
   ]
  },
  {
   "title": "Logistic System Storage",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_join(label_replace( (factorio_logistics_items{point_type=\"contents\", instance=\"localhost:$nodePort\", job=\"$jobName\"}>0), \"icon\", \"icon[$1]\", \"name\", \"(.*)\"), \"name_w_icon\", \" \", \"icon\", \"localised_name\")"
    }
   ]
  }
 ]
}