{
 "title": "Trains",
 "tags": [ "factorio" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "nodePort", "query": "9100" },
   { "name": "jobName", "query": "dev" }
  ]
 },
 "panels": [
  {
   "title": "Number of Trains",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(factorio_train_total{force=\"player\", instance=\"localhost:$nodePort\", job=\"$jobName\"})",
     "legendFormat": "Total number of trains"
    }
   ]
  },
  {
   "title": "Number of minutes spent travelling",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(factorio_train_traveling{instance=\"localhost:$nodePort\", job=\"$jobName\"}[5m])*80)",
     "legendFormat": "Time travelled"
    }
   ]
  },
  {
   "title": "Signal Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(factorio_train_waiting_signal{instance=\"localhost:$nodePort\", job=\"$jobName\"}[5m])*80)"
    }
   ]
  },
  {
   "title": "Station Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(factorio_train_waiting_station{instance=\"localhost:$nodePort\", job=\"$jobName\"}[5m])*80)",
     "legendFormat": "Time"
    }
   ]
  }
 ]
}